included:
  - Sources
  - Tests
trailing_comma:
    mandatory_comma: true
disabled_rules:
  - identifier_name
opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - implicit_return
  - unused_import
  - indentation_width
